FROM centos:centos6
MAINTAINER Nemanja Andrejevic <andrejevicnemanja@gmail.com>

# Update OS and installs basic tools
RUN yum -y update
RUN yum -y install wget curl telnet mc yum-utils

RUN yum clean all