#!/bin/bash

/usr/bin/mysql_install_db --user=mysql --defaults-file=/etc/my.cnf

/usr/bin/mysqld_safe --defaults-file=/etc/my.cnf &

sleep 3

mysql -u root -e " \
  SET PASSWORD = PASSWORD('mysql'); \
  UPDATE mysql.user SET password = PASSWORD('mysql') WHERE user = 'root'; \
  DELETE FROM mysql.user WHERE user = ''; \
  GRANT ALL ON *.* TO 'root'@'%' IDENTIFIED BY 'mysql' WITH GRANT OPTION;"